name: merge main to azure-main branch
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: merge main -> azure-main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main 
          target_branch: azure-main
          github_token: ${{ secrets.TOKEN }}
